//! `d3d9.dll` name → id rows for the dense WinAPI dispatch.
//!
//! Row order mirrors the `WinApiId` enum's `D3d9*` variants and
//! matches the pre-split dense table exactly, so each row keeps its original
//! discriminant mapping.

use crate::dispatch_table::WinApiId;

/// `d3d9.dll` rows in dense `WinApiId` order.
pub(super) const ROWS: &[(&str, &str, WinApiId)] = &[
    ("d3d9.dll", "direct3dcreate9", WinApiId::D3d9Direct3dcreate9),
    (
        "d3d9.dll",
        "idirect3d9::getadaptercount",
        WinApiId::D3d9Idirect3d9Getadaptercount,
    ),
    (
        "d3d9.dll",
        "idirect3d9::getadaptermonitor",
        WinApiId::D3d9Idirect3d9Getadaptermonitor,
    ),
    (
        "d3d9.dll",
        "idirect3d9::getdevicecaps",
        WinApiId::D3d9Idirect3d9Getdevicecaps,
    ),
    (
        "d3d9.dll",
        "idirect3d9::getadapterdisplaymode",
        WinApiId::D3d9Idirect3d9Getadapterdisplaymode,
    ),
    (
        "d3d9.dll",
        "idirect3d9::createdevice",
        WinApiId::D3d9Idirect3d9Createdevice,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::setvertexshader",
        WinApiId::D3d9Idirect3ddevice9Setvertexshader,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::setfvf",
        WinApiId::D3d9Idirect3ddevice9Setfvf,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::setrenderstate",
        WinApiId::D3d9Idirect3ddevice9Setrenderstate,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::settexturestagestate",
        WinApiId::D3d9Idirect3ddevice9Settexturestagestate,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::setsamplerstate",
        WinApiId::D3d9Idirect3ddevice9Setsamplerstate,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::release",
        WinApiId::D3d9Idirect3ddevice9Release,
    ),
    (
        "d3d9.dll",
        "idirect3d9::release",
        WinApiId::D3d9Idirect3d9Release,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::present",
        WinApiId::D3d9Idirect3ddevice9Present,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::beginscene",
        WinApiId::D3d9Idirect3ddevice9Beginscene,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::endscene",
        WinApiId::D3d9Idirect3ddevice9Endscene,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::clear",
        WinApiId::D3d9Idirect3ddevice9Clear,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::settransform",
        WinApiId::D3d9Idirect3ddevice9Settransform,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::setviewport",
        WinApiId::D3d9Idirect3ddevice9Setviewport,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::getviewport",
        WinApiId::D3d9Idirect3ddevice9Getviewport,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::drawprimitive",
        WinApiId::D3d9Idirect3ddevice9Drawprimitive,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::drawindexedprimitive",
        WinApiId::D3d9Idirect3ddevice9Drawindexedprimitive,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::drawprimitiveup",
        WinApiId::D3d9Idirect3ddevice9Drawprimitiveup,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::drawindexedprimitiveup",
        WinApiId::D3d9Idirect3ddevice9Drawindexedprimitiveup,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::setstreamsource",
        WinApiId::D3d9Idirect3ddevice9Setstreamsource,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::setindices",
        WinApiId::D3d9Idirect3ddevice9Setindices,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::createvertexbuffer",
        WinApiId::D3d9Idirect3ddevice9Createvertexbuffer,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::createindexbuffer",
        WinApiId::D3d9Idirect3ddevice9Createindexbuffer,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::createtexture",
        WinApiId::D3d9Idirect3ddevice9Createtexture,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::settexture",
        WinApiId::D3d9Idirect3ddevice9Settexture,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::gettexture",
        WinApiId::D3d9Idirect3ddevice9Gettexture,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::gettexturestagestate",
        WinApiId::D3d9Idirect3ddevice9Gettexturestagestate,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::getsamplerstate",
        WinApiId::D3d9Idirect3ddevice9Getsamplerstate,
    ),
    (
        "d3d9.dll",
        "idirect3dtexture9::getlevelcount",
        WinApiId::D3d9Idirect3dtexture9Getlevelcount,
    ),
    (
        "d3d9.dll",
        "idirect3dtexture9::getsurfacelevel",
        WinApiId::D3d9Idirect3dtexture9Getsurfacelevel,
    ),
    (
        "d3d9.dll",
        "idirect3dtexture9::lockrect",
        WinApiId::D3d9Idirect3dtexture9Lockrect,
    ),
    (
        "d3d9.dll",
        "idirect3dtexture9::unlockrect",
        WinApiId::D3d9Idirect3dtexture9Unlockrect,
    ),
    (
        "d3d9.dll",
        "idirect3dtexture9::release",
        WinApiId::D3d9Idirect3dtexture9Release,
    ),
    (
        "d3d9.dll",
        "idirect3dsurface9::lockrect",
        WinApiId::D3d9Idirect3dsurface9Lockrect,
    ),
    (
        "d3d9.dll",
        "idirect3dsurface9::unlockrect",
        WinApiId::D3d9Idirect3dsurface9Unlockrect,
    ),
    (
        "d3d9.dll",
        "idirect3dsurface9::release",
        WinApiId::D3d9Idirect3dsurface9Release,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::createdepthstencilsurface",
        WinApiId::D3d9Idirect3ddevice9Createdepthstencilsurface,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::setdepthstencilsurface",
        WinApiId::D3d9Idirect3ddevice9Setdepthstencilsurface,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::getdepthstencilsurface",
        WinApiId::D3d9Idirect3ddevice9Getdepthstencilsurface,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::getrenderstate",
        WinApiId::D3d9Idirect3ddevice9Getrenderstate,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::createvertexshader",
        WinApiId::D3d9Idirect3ddevice9Createvertexshader,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::getvertexshader",
        WinApiId::D3d9Idirect3ddevice9Getvertexshader,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::setvertexshaderconstantf",
        WinApiId::D3d9Idirect3ddevice9Setvertexshaderconstantf,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::getvertexshaderconstantf",
        WinApiId::D3d9Idirect3ddevice9Getvertexshaderconstantf,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::setvertexshaderconstanti",
        WinApiId::D3d9Idirect3ddevice9Setvertexshaderconstanti,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::getvertexshaderconstanti",
        WinApiId::D3d9Idirect3ddevice9Getvertexshaderconstanti,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::setvertexshaderconstantb",
        WinApiId::D3d9Idirect3ddevice9Setvertexshaderconstantb,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::getvertexshaderconstantb",
        WinApiId::D3d9Idirect3ddevice9Getvertexshaderconstantb,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::createpixelshader",
        WinApiId::D3d9Idirect3ddevice9Createpixelshader,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::setpixelshader",
        WinApiId::D3d9Idirect3ddevice9Setpixelshader,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::getpixelshader",
        WinApiId::D3d9Idirect3ddevice9Getpixelshader,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::setpixelshaderconstantf",
        WinApiId::D3d9Idirect3ddevice9Setpixelshaderconstantf,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::getpixelshaderconstantf",
        WinApiId::D3d9Idirect3ddevice9Getpixelshaderconstantf,
    ),
    (
        "d3d9.dll",
        "idirect3dpixelshader9::release",
        WinApiId::D3d9Idirect3dpixelshader9Release,
    ),
    (
        "d3d9.dll",
        "idirect3dvertexshader9::release",
        WinApiId::D3d9Idirect3dvertexshader9Release,
    ),
    // ── L2 buffer objects (appended after the D3d9* block — the row order
    // mirrors the enum discriminants, and these were appended at 464+).
    (
        "d3d9.dll",
        "idirect3dvertexbuffer9::queryinterface",
        WinApiId::D3d9Idirect3dvertexbuffer9Queryinterface,
    ),
    (
        "d3d9.dll",
        "idirect3dvertexbuffer9::addref",
        WinApiId::D3d9Idirect3dvertexbuffer9Addref,
    ),
    (
        "d3d9.dll",
        "idirect3dvertexbuffer9::release",
        WinApiId::D3d9Idirect3dvertexbuffer9Release,
    ),
    (
        "d3d9.dll",
        "idirect3dvertexbuffer9::lock",
        WinApiId::D3d9Idirect3dvertexbuffer9Lock,
    ),
    (
        "d3d9.dll",
        "idirect3dvertexbuffer9::unlock",
        WinApiId::D3d9Idirect3dvertexbuffer9Unlock,
    ),
    (
        "d3d9.dll",
        "idirect3dvertexbuffer9::getdesc",
        WinApiId::D3d9Idirect3dvertexbuffer9Getdesc,
    ),
    (
        "d3d9.dll",
        "idirect3dindexbuffer9::queryinterface",
        WinApiId::D3d9Idirect3dindexbuffer9Queryinterface,
    ),
    (
        "d3d9.dll",
        "idirect3dindexbuffer9::addref",
        WinApiId::D3d9Idirect3dindexbuffer9Addref,
    ),
    (
        "d3d9.dll",
        "idirect3dindexbuffer9::release",
        WinApiId::D3d9Idirect3dindexbuffer9Release,
    ),
    (
        "d3d9.dll",
        "idirect3dindexbuffer9::lock",
        WinApiId::D3d9Idirect3dindexbuffer9Lock,
    ),
    (
        "d3d9.dll",
        "idirect3dindexbuffer9::unlock",
        WinApiId::D3d9Idirect3dindexbuffer9Unlock,
    ),
    (
        "d3d9.dll",
        "idirect3dindexbuffer9::getdesc",
        WinApiId::D3d9Idirect3dindexbuffer9Getdesc,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::getstreamsource",
        WinApiId::D3d9Idirect3ddevice9Getstreamsource,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::getindices",
        WinApiId::D3d9Idirect3ddevice9Getindices,
    ),
    // ── L3 appended rows (getters + the scissor setter) — the variant order
    // mirrors the appended enum discriminants.
    (
        "d3d9.dll",
        "idirect3ddevice9::gettransform",
        WinApiId::D3d9Idirect3ddevice9Gettransform,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::multiplytransform",
        WinApiId::D3d9Idirect3ddevice9Multiplytransform,
    ),
    (
        "d3d9.dll",
        "idirect3ddevice9::setscissorrect",
        WinApiId::D3d9Idirect3ddevice9Setscissorrect,
    ),
];
