//! `kernel32.dll` name → id rows for the dense WinAPI dispatch.
//!
//! Row order mirrors the `WinApiId` enum's `Kernel32*` variants and
//! matches the pre-split dense table exactly, so each row keeps its original
//! discriminant mapping.

use crate::dispatch_table::WinApiId;

/// `kernel32.dll` rows in dense `WinApiId` order.
pub(super) const ROWS: &[(&str, &str, WinApiId)] = &[
    (
        "kernel32.dll",
        "getversionexa",
        WinApiId::Kernel32Getversionexa,
    ),
    (
        "kernel32.dll",
        "getmodulehandlea",
        WinApiId::Kernel32Getmodulehandlea,
    ),
    (
        "kernel32.dll",
        "getcommandlinea",
        WinApiId::Kernel32Getcommandlinea,
    ),
    (
        "kernel32.dll",
        "getcommandlinew",
        WinApiId::Kernel32Getcommandlinew,
    ),
    (
        "kernel32.dll",
        "getstartupinfoa",
        WinApiId::Kernel32Getstartupinfoa,
    ),
    (
        // Row placed with the appended variant (406), not after getstartupinfoa,
        // so the id table and the name rows stay in the same order.
        "kernel32.dll",
        "getstartupinfow",
        WinApiId::Kernel32Getstartupinfow,
    ),
    (
        "kernel32.dll",
        "getprocessheap",
        WinApiId::Kernel32Getprocessheap,
    ),
    (
        "kernel32.dll",
        "getsystemtimeasfiletime",
        WinApiId::Kernel32Getsystemtimeasfiletime,
    ),
    (
        "kernel32.dll",
        "getcurrentprocessid",
        WinApiId::Kernel32Getcurrentprocessid,
    ),
    (
        "kernel32.dll",
        "getcurrentthreadid",
        WinApiId::Kernel32Getcurrentthreadid,
    ),
    (
        "kernel32.dll",
        "gettickcount",
        WinApiId::Kernel32Gettickcount,
    ),
    (
        "kernel32.dll",
        "queryperformancecounter",
        WinApiId::Kernel32Queryperformancecounter,
    ),
    ("kernel32.dll", "heapalloc", WinApiId::Kernel32Heapalloc),
    ("kernel32.dll", "heapfree", WinApiId::Kernel32Heapfree),
    ("kernel32.dll", "heaprealloc", WinApiId::Kernel32Heaprealloc),
    ("kernel32.dll", "heapcreate", WinApiId::Kernel32Heapcreate),
    (
        "kernel32.dll",
        "heapsetinformation",
        WinApiId::Kernel32Heapsetinformation,
    ),
    (
        "kernel32.dll",
        "initializecriticalsection",
        WinApiId::Kernel32Initializecriticalsection,
    ),
    (
        "kernel32.dll",
        "entercriticalsection",
        WinApiId::Kernel32Entercriticalsection,
    ),
    (
        "kernel32.dll",
        "leavecriticalsection",
        WinApiId::Kernel32Leavecriticalsection,
    ),
    (
        "kernel32.dll",
        "deletecriticalsection",
        WinApiId::Kernel32Deletecriticalsection,
    ),
    ("kernel32.dll", "flsalloc", WinApiId::Kernel32Flsalloc),
    ("kernel32.dll", "flsfree", WinApiId::Kernel32Flsfree),
    ("kernel32.dll", "flssetvalue", WinApiId::Kernel32Flssetvalue),
    ("kernel32.dll", "flsgetvalue", WinApiId::Kernel32Flsgetvalue),
    (
        "kernel32.dll",
        "getstdhandle",
        WinApiId::Kernel32Getstdhandle,
    ),
    ("kernel32.dll", "getfiletype", WinApiId::Kernel32Getfiletype),
    (
        "kernel32.dll",
        "sethandlecount",
        WinApiId::Kernel32Sethandlecount,
    ),
    (
        "kernel32.dll",
        "getenvironmentstringsw",
        WinApiId::Kernel32Getenvironmentstringsw,
    ),
    (
        "kernel32.dll",
        "freeenvironmentstringsw",
        WinApiId::Kernel32Freeenvironmentstringsw,
    ),
    (
        "kernel32.dll",
        "widechartomultibyte",
        WinApiId::Kernel32Widechartomultibyte,
    ),
    (
        "kernel32.dll",
        "getlasterror",
        WinApiId::Kernel32Getlasterror,
    ),
    (
        "kernel32.dll",
        "setlasterror",
        WinApiId::Kernel32Setlasterror,
    ),
    ("kernel32.dll", "getacp", WinApiId::Kernel32Getacp),
    ("kernel32.dll", "getoemcp", WinApiId::Kernel32Getoemcp),
    ("kernel32.dll", "getcpinfo", WinApiId::Kernel32Getcpinfo),
    (
        "kernel32.dll",
        "isvalidcodepage",
        WinApiId::Kernel32Isvalidcodepage,
    ),
    (
        "kernel32.dll",
        "getstringtypew",
        WinApiId::Kernel32Getstringtypew,
    ),
    (
        "kernel32.dll",
        "multibytetowidechar",
        WinApiId::Kernel32Multibytetowidechar,
    ),
    (
        "kernel32.dll",
        "lcmapstringw",
        WinApiId::Kernel32Lcmapstringw,
    ),
    (
        "kernel32.dll",
        "getmodulefilenamea",
        WinApiId::Kernel32Getmodulefilenamea,
    ),
    (
        "kernel32.dll",
        "getmodulefilenamew",
        WinApiId::Kernel32Getmodulefilenamew,
    ),
    (
        "kernel32.dll",
        "setunhandledexceptionfilter",
        WinApiId::Kernel32Setunhandledexceptionfilter,
    ),
    ("kernel32.dll", "heapsize", WinApiId::Kernel32Heapsize),
    (
        "kernel32.dll",
        "loadlibrarya",
        WinApiId::Kernel32Loadlibrarya,
    ),
    (
        "kernel32.dll",
        "loadlibraryw",
        WinApiId::Kernel32Loadlibraryw,
    ),
    ("kernel32.dll", "freelibrary", WinApiId::Kernel32Freelibrary),
    (
        "kernel32.dll",
        "getprocaddress",
        WinApiId::Kernel32Getprocaddress,
    ),
    (
        "kernel32.dll",
        "getfileattributesa",
        WinApiId::Kernel32Getfileattributesa,
    ),
    (
        "kernel32.dll",
        "getfileattributesw",
        WinApiId::Kernel32Getfileattributesw,
    ),
    (
        "kernel32.dll",
        "findfirstfilew",
        WinApiId::Kernel32Findfirstfilew,
    ),
    (
        "kernel32.dll",
        "findfirstfilea",
        WinApiId::Kernel32Findfirstfilea,
    ),
    (
        "kernel32.dll",
        "findnextfilew",
        WinApiId::Kernel32Findnextfilew,
    ),
    (
        "kernel32.dll",
        "findnextfilea",
        WinApiId::Kernel32Findnextfilea,
    ),
    ("kernel32.dll", "findclose", WinApiId::Kernel32Findclose),
    (
        "kernel32.dll",
        "loadlibraryexa",
        WinApiId::Kernel32Loadlibraryexa,
    ),
    (
        "kernel32.dll",
        "loadlibraryexw",
        WinApiId::Kernel32Loadlibraryexw,
    ),
    (
        "kernel32.dll",
        "findresourcea",
        WinApiId::Kernel32Findresourcea,
    ),
    (
        "kernel32.dll",
        "loadresource",
        WinApiId::Kernel32Loadresource,
    ),
    (
        "kernel32.dll",
        "lockresource",
        WinApiId::Kernel32Lockresource,
    ),
    (
        "kernel32.dll",
        "sizeofresource",
        WinApiId::Kernel32Sizeofresource,
    ),
    (
        "kernel32.dll",
        "getsystemdefaultlangid",
        WinApiId::Kernel32Getsystemdefaultlangid,
    ),
    (
        "kernel32.dll",
        "getuserdefaultlangid",
        WinApiId::Kernel32Getuserdefaultlangid,
    ),
    (
        // Row placed with the appended variant (407) next to its family sibling,
        // not at the table end, so id table and name rows stay in the same order.
        "kernel32.dll",
        "getuserdefaultuilanguage",
        WinApiId::Kernel32Getuserdefaultuilanguage,
    ),
    (
        "kernel32.dll",
        "globalmemorystatus",
        WinApiId::Kernel32Globalmemorystatus,
    ),
    (
        "kernel32.dll",
        "getlocaltime",
        WinApiId::Kernel32Getlocaltime,
    ),
    ("kernel32.dll", "createfilew", WinApiId::Kernel32Createfilew),
    ("kernel32.dll", "createfilea", WinApiId::Kernel32Createfilea),
    ("kernel32.dll", "closehandle", WinApiId::Kernel32Closehandle),
    (
        "kernel32.dll",
        "getfileinformationbyhandle",
        WinApiId::Kernel32Getfileinformationbyhandle,
    ),
    (
        "kernel32.dll",
        "filetimetolocalfiletime",
        WinApiId::Kernel32Filetimetolocalfiletime,
    ),
    (
        "kernel32.dll",
        "filetimetosystemtime",
        WinApiId::Kernel32Filetimetosystemtime,
    ),
    (
        "kernel32.dll",
        "gettimezoneinformation",
        WinApiId::Kernel32Gettimezoneinformation,
    ),
    ("kernel32.dll", "getfiletime", WinApiId::Kernel32Getfiletime),
    (
        "kernel32.dll",
        "setfilepointer",
        WinApiId::Kernel32Setfilepointer,
    ),
    ("kernel32.dll", "getfilesize", WinApiId::Kernel32Getfilesize),
    (
        "kernel32.dll",
        "encodepointer",
        WinApiId::Kernel32Encodepointer,
    ),
    (
        "kernel32.dll",
        "decodepointer",
        WinApiId::Kernel32Decodepointer,
    ),
    (
        "kernel32.dll",
        "initializecriticalsectionandspincount",
        WinApiId::Kernel32Initializecriticalsectionandspincount,
    ),
    ("kernel32.dll", "readfile", WinApiId::Kernel32Readfile),
    ("kernel32.dll", "writefile", WinApiId::Kernel32Writefile),
    (
        "kernel32.dll",
        "getcurrentdirectoryw",
        WinApiId::Kernel32Getcurrentdirectoryw,
    ),
    (
        "kernel32.dll",
        "setcurrentdirectoryw",
        WinApiId::Kernel32Setcurrentdirectoryw,
    ),
    (
        "kernel32.dll",
        "getcurrentprocess",
        WinApiId::Kernel32Getcurrentprocess,
    ),
    ("kernel32.dll", "sleep", WinApiId::Kernel32Sleep),
    ("kernel32.dll", "localalloc", WinApiId::Kernel32Localalloc),
    ("kernel32.dll", "localfree", WinApiId::Kernel32Localfree),
    ("kernel32.dll", "globalalloc", WinApiId::Kernel32Globalalloc),
    ("kernel32.dll", "globalfree", WinApiId::Kernel32Globalfree),
    ("kernel32.dll", "globallock", WinApiId::Kernel32Globallock),
    (
        "kernel32.dll",
        "globalunlock",
        WinApiId::Kernel32Globalunlock,
    ),
    ("kernel32.dll", "globalsize", WinApiId::Kernel32Globalsize),
    ("kernel32.dll", "muldiv", WinApiId::Kernel32Muldiv),
    (
        "kernel32.dll",
        "globaladdatoma",
        WinApiId::Kernel32Globaladdatoma,
    ),
    (
        "kernel32.dll",
        "globaldeleteatom",
        WinApiId::Kernel32Globaldeleteatom,
    ),
    (
        "kernel32.dll",
        "getfullpathnamew",
        WinApiId::Kernel32Getfullpathnamew,
    ),
    (
        "kernel32.dll",
        "getfullpathnamea",
        WinApiId::Kernel32Getfullpathnamea,
    ),
    (
        "kernel32.dll",
        "getcurrentdirectorya",
        WinApiId::Kernel32Getcurrentdirectorya,
    ),
    (
        "kernel32.dll",
        "setcurrentdirectorya",
        WinApiId::Kernel32Setcurrentdirectorya,
    ),
    (
        "kernel32.dll",
        "createdirectoryw",
        WinApiId::Kernel32Createdirectoryw,
    ),
    (
        "kernel32.dll",
        "createdirectorya",
        WinApiId::Kernel32Createdirectorya,
    ),
    (
        "kernel32.dll",
        "removedirectoryw",
        WinApiId::Kernel32Removefirectoryw,
    ),
    (
        "kernel32.dll",
        "removedirectorya",
        WinApiId::Kernel32Removefirectorya,
    ),
    ("kernel32.dll", "deletefilew", WinApiId::Kernel32Deletefilew),
    ("kernel32.dll", "deletefilea", WinApiId::Kernel32Deletefilea),
    ("kernel32.dll", "movefilew", WinApiId::Kernel32Movefilew),
    ("kernel32.dll", "movefilea", WinApiId::Kernel32Movefilea),
    (
        "kernel32.dll",
        "gettemppathw",
        WinApiId::Kernel32Gettemppathw,
    ),
    (
        "kernel32.dll",
        "gettemppatha",
        WinApiId::Kernel32Gettemppatha,
    ),
    (
        "kernel32.dll",
        "gettempfilenamew",
        WinApiId::Kernel32Gettempfilenamew,
    ),
    (
        "kernel32.dll",
        "gettempfilenamea",
        WinApiId::Kernel32Gettempfilenamea,
    ),
    (
        "kernel32.dll",
        "getdrivetypew",
        WinApiId::Kernel32Getdrivetypew,
    ),
    (
        "kernel32.dll",
        "getdrivetypea",
        WinApiId::Kernel32Getdrivetypea,
    ),
    (
        "kernel32.dll",
        "getlogicaldrives",
        WinApiId::Kernel32Getlogicaldrives,
    ),
    (
        "kernel32.dll",
        "getsystemdirectoryw",
        WinApiId::Kernel32Getsystemdirectoryw,
    ),
    (
        "kernel32.dll",
        "getsystemdirectorya",
        WinApiId::Kernel32Getsystemdirectorya,
    ),
    (
        "kernel32.dll",
        "getwindowsdirectoryw",
        WinApiId::Kernel32Getwindowsdirectoryw,
    ),
    (
        "kernel32.dll",
        "getwindowsdirectorya",
        WinApiId::Kernel32Getwindowsdirectorya,
    ),
    (
        "kernel32.dll",
        "getfilesizeex",
        WinApiId::Kernel32Getfilesizeex,
    ),
    (
        "kernel32.dll",
        "setfilepointerex",
        WinApiId::Kernel32Setfilepointerex,
    ),
    (
        "kernel32.dll",
        "setendoffile",
        WinApiId::Kernel32Setendoffile,
    ),
    (
        "kernel32.dll",
        "flushfilebuffers",
        WinApiId::Kernel32Flushfilebuffers,
    ),
    (
        "kernel32.dll",
        "writeconsolew",
        WinApiId::Kernel32Writeconsolew,
    ),
    (
        "kernel32.dll",
        "writeconsolea",
        WinApiId::Kernel32Writeconsolea,
    ),
    (
        "kernel32.dll",
        "readconsolew",
        WinApiId::Kernel32Readconsolew,
    ),
    (
        "kernel32.dll",
        "readconsolea",
        WinApiId::Kernel32Readconsolea,
    ),
    (
        "kernel32.dll",
        "getconsolemode",
        WinApiId::Kernel32Getconsolemode,
    ),
    (
        "kernel32.dll",
        "setconsolemode",
        WinApiId::Kernel32Setconsolemode,
    ),
    (
        "kernel32.dll",
        "writeconsoleoutputw",
        WinApiId::Kernel32Writeconsoleoutputw,
    ),
    (
        "kernel32.dll",
        "fillconsoleoutputcharacterw",
        WinApiId::Kernel32Fillconsoleoutputcharacterw,
    ),
    (
        "kernel32.dll",
        "setconsolecursorposition",
        WinApiId::Kernel32Setconsolecursorposition,
    ),
    (
        "kernel32.dll",
        "setconsoletextattribute",
        WinApiId::Kernel32Setconsoletextattribute,
    ),
    (
        "kernel32.dll",
        "gettickcount64",
        WinApiId::Kernel32Gettickcount64,
    ),
    (
        "kernel32.dll",
        "getenvironmentvariablew",
        WinApiId::Kernel32Getenvironmentvariablew,
    ),
    (
        "kernel32.dll",
        "setenvironmentvariablew",
        WinApiId::Kernel32Setenvironmentvariablew,
    ),
    (
        // Rows placed at the table end with the appended variants (438/439),
        // so the id table and the name rows stay in the same order.
        "kernel32.dll",
        "locallock",
        WinApiId::Kernel32Locallock,
    ),
    ("kernel32.dll", "localunlock", WinApiId::Kernel32Localunlock),
    (
        // Rows placed at the table end with the appended variants (440/441),
        // so the id table and the name rows stay in the same order.
        "kernel32.dll",
        "gettimeformatw",
        WinApiId::Kernel32Gettimeformatw,
    ),
    (
        "kernel32.dll",
        "getdateformatw",
        WinApiId::Kernel32Getdateformatw,
    ),
];
